[package]
name = "eventually"
description = "Crate for using Event Sourcing in Rust applications"
version = "0.4.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/eventually-rs/eventually-rs"

categories = ["rust-patterns", "web-programming", "asynchronous", "data-structures"]
keywords = ["architecture", "ddd", "event-sourcing", "cqrs", "es"]

[features]
default = []
tracing = ["eventually-util/with-tracing"]
full = ["serde", "tracing"]

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
eventually-util = { version = "0.4.0", path = "../eventually-util" }
futures = "0.3.17"
serde = { version = "1.0.130", optional = true, features = ["derive"] }
thiserror = "1.0.29"

[dev-dependencies]
async-trait = "0.1.51"
futures = { version = "0.3", features = ["async-await"] }
tokio-test = "0.4.2"
